language: rust
cache: cargo
dist: trusty
os:
- linux
- osx
rust:
- nightly
- stable
script:
- cargo build
- cargo test -- --color always --nocapture
env:
    - secure: F00739kjbvPiRGcd5qNatY1+LAmWdTgD61/GGGIT087wMdz1BG9CKr5mXlZNP5DgOtFCG3hLTnYLSMW/T6Zt4Gzx1Hze290eOunYchx8YR6xs3TlWnMvnQLcbSyjTQBdnRx28tGLkrAByXYp/3ZdIIKa0usqxE8QYMiiXYgGGYI12dRZ6c4fUNdHh3kr4b9srHacPKW80IXYImFd8K1zrpfEeJvmnRtcqdwYbqRbL/9GyRIcEMF3y6GcIUN0awHAobCXVVQmgjqun6Wf4Y84bwWqq+oJbrI5bwXrYc0/cg1tXGBPvNIedw03aoShz9yOiDOGzYRPfAjYFpyWHdLXhzkVTkH/+bCL2PUjzTjQGBpglohtuPCTocqbmFgxVQqRB+klG5iK251X4CP/g7Ljuzbsvoy4ZP5J1N7I1urQZ2IysXxRR8TAA7p5Q85ZS7cyoHv0otSTXRMxm+0pAcAnXGK3KoB6t3NwicS/EHIAUknagrQOp3GBXCT363McnwEeIgqvLxUm48KZDAT+PN5xgCKFUu+QRhV8mIIKtWlitkWvJA8keCvSqNhqOIJ6+q10m1QVeyIiK4oVb2LOH+blGOLaRzYukxB8AGw3Y1AWW7UOx/AAnQRF05ruNUhulYIzuBAIVsVWzWTbPPr+JNo2s3wrYV2x4d+tT0BjHyhlPI8=
