[package]
name = "narwhalol"
description = "Easy to use async/sync League of legends API Wrapper"
keywords = ["api", "http"]
version = "0.2.1"
authors = ["Kirill Mironov <arkrait04@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Drevoed/narwhal"
documentation = "https://docs.rs/narwhalol"
homepage = "https://narwhal.arkrait.tech"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[badges]
travis-ci = {repository = "Drevoed/narwhal", branch = "master"}
codecov = {repository = "Drevoed/narwhal", branch = "master", service = "github"}

[dependencies]
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
log = "0.4.8"
snafu = {version = "0.5.0", features = ["unstable-futures"]}
snafu-derive = "0.5.0"
env_logger = "0.6.2"
tokio = "0.2.0-alpha.6"
futures-preview = "0.3.0-alpha.19"
hyper = {version = "0.13.0-alpha.4", features = ["unstable-stream"]}
hyper-tls = "0.4.0-alpha.4"
async-trait = "0.1.13"
