[package]
name = "narwhalol"
description = "Easy to use async/sync League of legends API Wrapper"
keywords = ["api", "http"]
version = "0.1.2"
authors = ["Kirill Mironov <arkrait04@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Drevoed/narwhal"
documentation = "https://docs.rs/narwhalol"
homepage = "https://narwhal.arkrait.tech"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[badges]
travis-ci = {repository = "Drevoed/narwhal", branch = "master"}
codecov = {repository = "Drevoed/narwhal", branch = "master", service = "github"}

[dependencies]
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
reqwest = {version = "0.9.19", optional = true}
lazy_static = "1.3.0"
hyper = {version = "0.12.33", optional = true}
log = "0.4.8"
snafu = "0.4.4"

[features]
default = ["synchronous"]

synchronous = ["reqwest"]

asynchronous = ["hyper"]
