[package]
name = "narwhalol"
description = "Easy to use async/sync League of legends API Wrapper"
keywords = ["api", "http"]
version = "0.1.2"
authors = ["Kirill Mironov <arkrait04@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Drevoed/narwhal"
documentation = "https://docs.rs/narwhalol"
homepage = "https://narwhal.arkrait.tech"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[badges]
travis-ci = {repository = "Drevoed/narwhal", branch = "master"}
codecov = {repository = "Drevoed/narwhal", branch = "master", service = "github"}

[dependencies]
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
hyper = "0.12.33"
hyper-tls = "0.3.2"
log = "0.4.8"
snafu = { version = "0.4", features = ["futures-01"]}
futures = "0.1.28"
env_logger = "0.6.2"
tokio = "0.1.22"
