[package]
name = "narwhal"
description = ""
version = "0.1.0"
authors = ["Kirill Mironov <arkrait04@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"


[dependencies]
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
reqwest = {version = "0.9.19", optional = true}
lazy_static = "1.3.0"
hyper = {version = "0.12.33", optional = true}
log = "0.4.8"

[features]
default = ["sync"]

sync = ["reqwest"]

async = ["hyper"]